# Generated by Django 4.2.1 on 2023-05-23 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bill_card_remove_user_payment_amount_and_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_on',
            field=models.DateField(auto_now=True),
        ),
    ]
