# Generated by Django 4.2.1 on 2023-05-24 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Customuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
