# Generated by Django 4.2.1 on 2023-05-24 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_schedule_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Customuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
