# Generated by Django 4.2.1 on 2023-05-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_schedule_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='expiry_month',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiry_year',
        ),
    ]
