# Generated by Django 4.2.1 on 2023-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_expiry_month_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.CharField(max_length=200),
        ),
    ]
