# Generated by Django 4.2.1 on 2023-05-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_bill_status_alter_card_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bill'),
        ),
    ]
