# Generated by Django 4.2.1 on 2023-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reply',
        ),
        migrations.AddField(
            model_name='complaints',
            name='reply_complaint',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
