# Generated by Django 4.2.1 on 2023-07-12 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_delete_reply_complaints_reply_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_types',
            name='Customuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
