# Generated by Django 4.2.1 on 2023-07-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_work_types_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_types',
            name='Customuser',
        ),
        migrations.AddField(
            model_name='schedule',
            name='type_of_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.work_types'),
        ),
    ]
