# Generated by Django 4.2.1 on 2023-07-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_work_types_customuser_schedule_type_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type_of_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='myapp.work_types'),
        ),
    ]
