# Generated by Django 4.2.1 on 2023-07-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_schedule_type_of_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
