# Generated by Django 4.2.1 on 2023-07-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_customuser_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_accepted',
        ),
    ]
