# Generated by Django 4.2.1 on 2023-09-08 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='complaints',
            name='reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
